### ISSUE TITLE
第七章是不是少了前三部分

### ISSUE THREAD

**Issue by DendiHust** [qyyzm/hdgy#1]
你好，第七章是不是少了前三部分？

**Comment by qyyzm** [comment]
有些东西，知道了比不知道，更好。缺掉的内容，主要是在聊符（文字）咒（语言），其实很多年前公开过这些内容，但本文档较正规，不能公开讨论这些东西，请理解、请体谅。
又，先生您，到底是华科大的老师还是学生？？冒昧了，有点原因，才会问您这问题！

**Comment by DendiHust** [comment]
感谢先生的回复，理解您的用心。读您的《昧道谭丛》和《衡道裁影》很受启发，在此表示感谢。

我是华中科技大学的硕士研究生，现已经毕业参加工作。

**Comment by qyyzm** [comment]
谢谢支持！哈哈～学长已工作，恭喜恭喜～～家里小朋友在华科大光电本硕博大三，本来以为可以套套近乎，多多关照一下小朋友的～哈哈～～～～问好ing~~~

**Comment by DendiHust** [comment]
哈哈，华科光电很棒的，恭喜学弟。
